### ISSUE TITLE
Alignment Issues

### ISSUE THREAD

**Issue by bucketpress** [marcusig/gutenberg-section-block#11]
On the backend editor, data-align=full is set by default, but frontend is rendered as normal. This causes confusion.

Furthermore, it will be useful if this block supports 'align: true', and specifically allows user to choose 'alignwide' or 'alignfull', similarly to a Cover block. Just not too sure whether align left, right and center will be useful, but alignwide and align full is surely needed for most users.

**Comment by marcusig** [comment]
Merged in https://github.com/marcusig/gutenberg-section-block/pull/12
