### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by Jaydeep-Trivedi** [marcusig/gutenberg-section-block#15]
Hi There,

I would like to fork this plugin for use in my software. However, there doesn't seem to be a license file added to this project. Could you please add a license file so that I can figure out how to proceed with this?

Thanks.

**Comment by marcusig** [comment]
@Jaydeep-Trivedi I've now added a license file.

**Comment by Jaydeep-Trivedi** [comment]
@marcusig Thanks a lot :)
