### ISSUE TITLE
Block broken on Wordpress 5.4 update

### ISSUE THREAD

**Issue by aaron051** [marcusig/gutenberg-section-block#18]
The block is forcing me to 'Keep as HTML' on every instance on every page after updating to Wordpress 5.4

**Comment by whitneykrape** [comment]
Will try and put together a proper pull request but some of the references are behind. Did a quick rebuild after changing:
index.js
Change withColors to pull from blockEditor:
`const {
	withColors,
} = wp.editor;`
to:
`const {
	withColors,
} = wp.blockEditor;`

Then in the init.php the "wp-editor" needs to be pulled explicitly. Change:
`array( 'wp-block-library', 'wp-i18n', 'wp-element' ), // Dependencies, defined above.`
to:
`array( 
			'wp-block-library', 
			'wp-editor',
			'wp-blocks',
			'wp-i18n',
			'wp-element', 
		), `

There are some other dependencies that need to be updated also but that should get the plugin running. (Probably don't need to have have both "block-library" and "wp-blocks" but it did build and does work.)

**Comment by aaron051** [comment]
Thanks a million. 

That did the job to get it back functioning so I can edit content again.

**Comment by marcusig** [comment]
Hi there,

Sorry, I haven't been very active on this plugin, as I expected a similar one to be included in WP core.

@whitneykrape I updated the plugin with your fix, as well as other updates and fixes. Hopefully this works out.

**Comment by swinggraphics** [comment]
@marcusig I thought so, too. Maybe it's still in the beta set of changes intended for "full site editing"?

**Comment by aaron051** [comment]
@marcusig thanks for the update. Much appreciated
