### ISSUE TITLE
JS Error on latest WP and ACF

### ISSUE THREAD

**Issue by mountbatt** [marcusig/gutenberg-section-block#19]
Hi,

i have a website that runs with your section-block plugin. Since the latest updates of WP I can't add an image in an ACF-Field anymore when the block-plugin is enabled. 

Question 1: how an I replace the created section blocks very simple today? Is there a core section block in Gutenberg?

or
Question 2: how can i fix the problem (or can you fix it?)

![Bildschirmfoto 2021-03-03 um 12 24 52](https://user-images.githubusercontent.com/2411246/109798790-798a4c80-7c1b-11eb-8dfe-505db8a13f4f.png)

As you can see in my screenshot: if i click on "Bild hinzufügen" the media popup does not open. Instead an error message comes up in console.

``
TypeError:` _.contains is not a function. (In '_.contains(r.allowed,e.orderby)', '_.contains' is undefined)
``

**Comment by mountbatt** [comment]
Can anyone help? Cant work in my Website since 7 days …

**Comment by marcusig** [comment]
Hi @mountbatt,

Sorry I haven't had the time to look at this. 
Does your setup require the premium version of ACF ?

**Comment by mountbatt** [comment]
@marcusig  Yes, ACF Pro. I can send you credentials etc. if you need … or test things four you … you can email me, if needed … mountbatt@gmail.com – maybe we find a solution. Thanks!

**Comment by mountbatt** [comment]
Hi, @marcusig can you tell me how to replace this section plugin with others on a live site? Is there a Gutenberg core equivalent?

**Comment by marcusig** [comment]
Hi,
I don't think there's quite the equivalent yet. 
The "Group" can work as a simplified version, it just doesn't have as many options, such as spacing or background image.

I tested locally with the free version of ACF and did't see any issue.
I'll send you an email, maybe you can send me some credentials so I can check what's happening.

**Comment by mountbatt** [comment]
HI @marcusig , thanks for checking it. I made a manual update with the latest files from GitHub and now it works. THANKS.
