### ISSUE TITLE
Styling and wrap suggestions

### ISSUE THREAD

**Issue by martinbon** [marcusig/gutenberg-section-block#2]
I've tested the section block and thought of a few improvements that would make the section block significantly more useful:

- 'wp-block-mkl-section-block' overrides the "wrap" class for us from 'additional CSS class' field. Shouldn't do that. Perhaps have a section block option that would allow to wrap the content without having nested sections?

- Text colour option could also go along with background colour option, since going in and changing the colour for each paragraph can get very cumbersome for long content

- HTML style option, where you can edit the section style (padding, margins, etc).

cc @lkraav

**Comment by lkraav** [comment]
@martinbon are you able to clarify your intentions with some example HTML code blocks here (esp. expected wrap structure)?

**Comment by marcusig** [comment]
@martinbon thanks for the suggestions. 

 I don't see the 'additional css class' being overridden: 

![image](https://user-images.githubusercontent.com/11990914/43641770-30f03e9a-9725-11e8-8090-b3ee3d07a61d.png)

I'm not sure what you mean by that:

> Perhaps have a section block option that would allow to wrap the content without having nested sections?

**Comment by martinbon** [comment]
@marcusig the wrap that was added using the "Additional CSS Class" is being overwritten by max-width of the section block parameters.
![Wrap class parameters](https://i.gyazo.com/458bc68f77311417899a763af706c85b.png)

**Comment by lkraav** [comment]
@martinbon means inline styles are overriding our class styles too aggressively.
