### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by swinggraphics** [marcusig/gutenberg-section-block#7]
After adding a section block and saving the post, the next time I try to edit it, I just get a blank page. Twentyseventeen with Gutenberg 4.0.

> TypeError: "R is not a function"
> save   http://localhost/wordpress/wp-content/plugins/gutenberg-section-block/dist/blocks.build.js?ver=1:1:6135
> 
> Unhandled promise rejection TypeError: "R is not a function"
> save   http://localhost/wordpress/wp-content/plugins/gutenberg-section-block/dist/blocks.build.js?ver=1:1:6135

**Comment by shelkie** [comment]
The "getColorClass" function in the Gutenberg plugin was renamed in version 4: [https://github.com/WordPress/gutenberg/pull/9355/files](https://github.com/WordPress/gutenberg/pull/9355/files)

A hacky fix is to open "/plugins/guterberg-section-block/dist/blocks.build.js", find the reference to "getColorClass" and rename it to "getColorClassName"

**Comment by kaha-digital** [comment]
Hey all - I have created a fork and fixed this - will issue a pull request shortly.
